export const SERVER_ENVIRONMENT = Symbol("SERVER_ENVIRONMENT");
export const DATABASE_CONNECTION = Symbol("DATABASE_CONNECTION");
export const DATABASE_CLOSE = Symbol("DATABASE_CLOSE");
export const REDIS_CONNECTION = Symbol("REDIS_CONNECTION");
